input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
    skip_on_invalid_json => true
  }

  mutate {
    rename => { "level" => "log_level" }
    remove_field => ["event", "input", "agent", "ecs", "host", "tags", "@version", "level_value", "logger_name", "thread_name"]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "employee-service-logs-%{+yyyy.MM.dd}"
  }
}
